In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\farhaan\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\farhaan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\farhaan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\farhaan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\farhaan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\farhaan\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd

In [3]:
df = pd.DataFrame(
    {
        'Place' : ['Home', 'Market', 'Mall', 'School'],
        'Time' : ['0', '10', '20', '10'],
        'Yes' : [1,0,0,1]
    }
)

In [4]:
print(df)

    Place Time  Yes
0    Home    0    1
1  Market   10    0
2    Mall   20    0
3  School   10    1

In [23]:
all_menu = pd.read_csv(r'C:\Users\Farhaan\Desktop\all-menu.csv')

In [24]:
all_drinks = pd.read_csv(r'C:\Users\Farhaan\Desktop\nutrition-drinks.csv')

In [13]:
all_menu.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [14]:
all_drinks.head()

,Unnamed: 0,Calories,Fat (g),Carb. (g),Fiber (g),Protein,Sodium
0,Cool Lime Starbucks Refreshers™ Beverage,45,0,11,0,0,10
1,Ombré Pink Drink,-,-,-,-,-,-
2,Pink Drink,-,-,-,-,-,-
3,Strawberry Acai Starbucks Refreshers™ Beverage,80,0,18,1,0,10
4,Very Berry Hibiscus Starbucks Refreshers™ Beve...,60,0,14,1,0,10

In [15]:
all_menu_venti = all_menu[all_menu['Beverage_prep']=='Venti']

In [16]:
all_menu_venti.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
43,Classic Espresso Drinks,Caffè Americano,Venti,25,0,0.0,0.0,0,15,4,0,0,1.0,0%,0%,2%,0%,300
101,Signature Espresso Drinks,Caramel Apple Spice (Without Whipped Cream),Venti,360,0,0.0,0.0,0,25,89,0,83,0.0,0%,0%,0%,0%,0
105,Tazo® Tea Drinks,Tazo® Tea,Venti,0,0,0.0,0.0,0,0,0,0,0,0.0,0%,0%,0%,0%,Varies
156,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),Venti,130,0.1,0.0,0.0,0,5,31,0,31,0.4,0%,0%,0%,0%,235

In [17]:
all_menu_venti_above100 = all_menu_venti[all_menu_venti['Calories']>100]

In [18]:
all_menu_venti_above100.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
101,Signature Espresso Drinks,Caramel Apple Spice (Without Whipped Cream),Venti,360,0,0.0,0.0,0,25,89,0,83,0.0,0%,0%,0%,0%,0
156,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),Venti,130,0.1,0.0,0.0,0,5,31,0,31,0.4,0%,0%,0%,0%,235
168,Shaken Iced Beverages,Shaken Iced Tazo® Tea (With Classic Syrup),Venti,120,0,0.0,0.0,0,0,31,0,31,0.0,0%,0%,0%,0%,Varies
171,Shaken Iced Beverages,Shaken Iced Tazo® Tea Lemonade (With Classic S...,Venti,190,0,0.0,0.0,0,0,49,0,49,0.1,0%,20%,0%,0%,Varies

In [14]:
lunch_menu = pd.read_csv(r'C:\Users\Farhaan\Desktop\ashoka\assignment1.csv')

In [15]:
lunch_menu.head()

  FOOD ITEM  CALORIES    INGREDIENTS  prep time
0   risotto     410.0  vegetable oil       30.0
1   risotto       NaN         butter        NaN
2   risotto       NaN           rice        NaN
3   risotto       NaN           salt        NaN
4   risotto       NaN   black pepper        NaN

In [16]:
dish_above400 = lunch_menu[lunch_menu["CALORIES"]>400]

In [17]:
dish_above400.head()

                 FOOD ITEM  CALORIES    INGREDIENTS  prep time
0                  risotto     410.0  vegetable oil       30.0
8           chicken quiche     439.0         onions       50.0
48  basil chicken and rice     421.0         cloves       50.0

In [21]:
dish_useOnions = lunch_menu[lunch_menu["INGREDIENTS"]=="onions"]

In [22]:
dish_useOnions.head()

         FOOD ITEM  CALORIES INGREDIENTS  prep time
8   chicken quiche     439.0      onions       50.0
29      Quesadilla       NaN      onions        NaN
44     papdi chaat       NaN      onions        NaN